@startuml

hide members
hide circle

skinparam ClassArrowColor Black
skinparam ClassBorderColor Black
skinparam ClassFontColor Black
skinparam ClassFontName "Calibri Normal"
skinparam ClassFontSize 18
skinparam ClassBackgroundColor #ebe2d4
skinparam ClassBorderThickness 2
skinparam Shadowing false
skinparam Padding 4
skinparam SameClassWidth true


together {
    class "Computing\nSystem"
    class "Processing\nSystem"
    class Resource
}

together {
    class Application
    class "Application\nUnit"
}

Application *--> "Application\nProcess"
Application *-> "Application\nUnit"
"Processing\nSystem" *-> Application
"Application\nProcess" *-> "Application\nTask"

"Application\nUnit" ..> "Application\nTask" : "executes as"

"Application\nTask" .> Resource : manages

"Computing\nSystem" *--> "Processing\nSystem"
"Processing\nSystem" *--> "Resource"


@enduml
