@startuml

hide members
hide circle

skinparam ClassArrowColor Black
skinparam ClassBorderColor Black
skinparam ClassFontColor Black
skinparam ClassFontName "Calibri Normal"
skinparam ClassFontSize 18
skinparam ClassBackgroundColor #ebe2d4
skinparam ClassBorderThickness 2
skinparam Shadowing false
skinparam Padding 4
skinparam SameClassWidth true


Infrastructure <|-- "DAF\nManagement"
Infrastructure <|-- "RIB\nDaemon"

"Distributed\nApplication\nUnit" *--> "DAF\nManagement"
"Distributed\nApplication\nUnit" *--> "RIB\nDaemon"



@enduml
