@startuml

hide members
hide circle

skinparam ClassArrowColor Black
skinparam ClassBorderColor Black
skinparam ClassFontColor Black
skinparam ClassFontName "Calibri Normal"
skinparam ClassFontSize 18
skinparam ClassBackgroundColor #ebe2d4
skinparam ClassBorderThickness 2
skinparam Shadowing false
skinparam Padding 4
skinparam SameClassWidth true


Unit <|-- "Application\nUnit"
Unit <|-- Infrastructure
Unit <|-- Atomic
Unit <|-- Composite

"Application\nUnit" <|-- "Distributed\nApplication Unit"

Composite *--> Unit

Unit *--> Policy
Unit *--> Interface

Policy <|-- Parameter
Policy <|-- Strategy
Policy <|-- "Decision\nPolicy"

@enduml
